### ISSUE TITLE
Server error, status code: 400, error code: 270011, message: p-mongodb-broker.bosh-lite.com is not a valid URL

### ISSUE THREAD

**Issue by abhilash07** [comxtohr/cf-mongo-release#1]
hi i successfully deployed all jobs and successfully runs  bosh run errand replset, on local bosh-lite warden environment. i am getting error while i am running bosh run errand broker-registrar. In below i have attached my deployment yaml file for your reference. Thanks in adnace
[mongo.txt](https://github.com/FoOTOo/cf-mongo-release/files/966616/mongo.txt)

**Comment by ultragtx** [comment]
Hi @abhilash07 , you should add `http://` or `https://` to `properties.broker.host`

The broker-registrar uses this command to create broker:
`cf create-service-broker $SERVICE_NAME $BROKER_USERNAME $BROKER_PASSWORD $BROKER_URL` 

You can run it directly in your shell, and will find  if `$BROKER_URL` does not begin with `http://` or `https://`, it will fail with the `... not a valid URL` error.

**Comment by abhilash07** [comment]
hi thanks for your quick response i changed my yml file and reploy but i am getting this error. 
![mongo-broker-err](https://cloud.githubusercontent.com/assets/10971841/25598487/3f21ecd0-2f10-11e7-9863-b5b01adc5faf.png)
[mongo.txt](https://github.com/FoOTOo/cf-mongo-release/files/969013/mongo.txt)

**Comment by ultragtx** [comment]
`port` in `properties.route_registrar` should be `80` instead of `8914`.

The broker currently listens on port `80`, and it's hard coded, if you want to change, you can modify the port here: https://github.com/FoOTOo/cf-mongodb-broker/blob/master/main.go#L72

**Comment by abhilash07** [comment]
thanks for your information, i have small doubt is this release can support
high-availability ?.
